name: Fuel Price Autoupdater
on:
  schedule:
    - cron: "0 22 * * *" # Runs daily (10 PM UTC is 6 AM Manila time)
  workflow_dispatch: # Allows you to run it manually from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - run: node scripts/updatePrices.js
        env:
          VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
